source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'LDZFAlertDialog_Example' do
  pod 'LDZFAlertDialog', :path => '../'
  target 'LDZFAlertDialog_Tests' do
    inherit! :search_paths

    
  end
end
